{{- if and (not .Values.existingConfigMap) (not .Values.existingSecret) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glauth.fullname" . }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
data:
  config.cfg: |
    {{- .Values.config | nindent 4 }}
{{- end }}
