apiVersion: v1
kind: Service
metadata:
  name: {{ include "glauth.fullname" . }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ldap
      port: {{ .Values.service.ports.ldap.port }}
      targetPort: ldap
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.ldap.nodePort }}
      nodePort: {{ .Values.service.ports.ldap.nodePort }}
      {{- end }}
    {{- if .Values.service.ports.ldaps.enabled }}
    - name: ldaps
      port: {{ .Values.service.ports.ldaps.port }}
      targetPort: ldaps
      protocol: TCP
    {{- end }}
    {{- if .Values.service.ports.api.enabled }}
    - name: api
      port: {{ .Values.service.ports.api.port }}
      targetPort: api
      protocol: TCP
    {{- end }}
  selector:
    {{- include "glauth.selectorLabels" . | nindent 4 }}
